### ISSUE TITLE
EXT-1 Nothing is returned in openClosePort() when exception happens

### ISSUE THREAD

**Issue by Bef0re9217** [JayHeng/JaysPyCOM#1]
I've been download your serial prot assistant based on pySerial+wxPython to learn.Thank you for share.But I found there are some problem in file jayspycom_main.py,line 121.The return is empty.Can you check it and give me a respond.
    Thank you very much!

**Comment by JayHeng** [comment]
Hi, sorry to reply so later, the return in line 123 means something is wrong, so we just exit openClosePort() directly, it is not an issue
